### ISSUE TITLE
10.11 Doesn't work anymore

### ISSUE THREAD

**Issue by heubergen** [miho/SonoAir#10]
<img width="653" alt="bildschirmfoto 2015-07-13 um 18 00 32" src="https://cloud.githubusercontent.com/assets/5529410/8654174/17bdef6a-2989-11e5-8edc-8645c6e5f6bf.png">
Hi, since the update to the public beta of Mac El Capitan (10.11) SonoAir doesn't work anymore correctly.

What works:
The App found the devices correctly
In the iTunes App I can choice the AirPlay-Device

What doesn't work:
I can not set the AirPlay-Device in the system settings audio.
When I try to play a song over iTunes I become a error message (-15000)

**Comment by Steviegal** [comment]
I have same problem with beta 4

**Comment by miho** [comment]
Thanks for the information. El Capitan support is a known problem. Unfortunately, Apple does not document the AirPlay related changes. My hope is that we get that information before El Capitan comes out. 

Please keep testing with new El Capitan releases and report your experiences here.

Thanks.

**Comment by Endogen** [comment]
Just installed El Capitan and SonoAir recognizes my devices but i can't see the AirPlay entry in system settings under sound output.

**Comment by KarimGeiger** [comment]
+1

**Comment by heubergen** [comment]
Still not work with 10.11.1 Beta (15B38b) and SonoAir Beta 4.0

LED control works fine.

What I did:
1) Start SonoAir
2) LED from Off to On
3) LED from On to Off
4) Try to play music from iTunes
5) Try to choice the SonoAir speaker in iTunes and then start to play music

Here my log: (may it help)

> > DEBUG: retryCounter: 0
> > DEBUG: using new discovery method
> > Okt 19, 2015 7:59:57 PM org.fourthline.cling.UpnpServiceImpl <init>
> > INFORMATION: >>> Starting UPnP service...
> > Okt 19, 2015 7:59:57 PM org.fourthline.cling.UpnpServiceImpl <init>
> > INFORMATION: Using configuration: org.fourthline.cling.DefaultUpnpServiceConfiguration
> > Okt 19, 2015 7:59:57 PM org.fourthline.cling.transport.RouterImpl <init>
> > INFORMATION: Creating Router: org.fourthline.cling.transport.RouterImpl
> > Okt 19, 2015 7:59:58 PM org.fourthline.cling.transport.impl.MulticastReceiverImpl init
> > INFORMATION: Creating wildcard socket (for receiving multicast datagrams) on port: 1900
> > Okt 19, 2015 7:59:58 PM org.fourthline.cling.transport.impl.MulticastReceiverImpl init
> > INFORMATION: Joining multicast group: /239.255.255.250:1900 on network interface: en3
> > Okt 19, 2015 7:59:58 PM org.fourthline.cling.transport.impl.StreamServerImpl init
> > INFORMATION: Created server (for receiving TCP streams) on: /192.168.88.253:49392
> > Okt 19, 2015 7:59:58 PM org.fourthline.cling.transport.impl.DatagramIOImpl init
> > INFORMATION: Creating bound socket (for datagram input/output) on: /192.168.88.253
> > Okt 19, 2015 7:59:58 PM org.fourthline.cling.UpnpServiceImpl <init>
> > INFORMATION: <<< UPnP service started successfully
> > Okt 19, 2015 7:59:58 PM org.fourthline.cling.UpnpServiceImpl <init>
> > INFORMATION: >>> Starting UPnP service...
> > Okt 19, 2015 7:59:58 PM org.fourthline.cling.UpnpServiceImpl <init>
> > INFORMATION: Using configuration: org.fourthline.cling.DefaultUpnpServiceConfiguration
> > Okt 19, 2015 7:59:58 PM org.fourthline.cling.transport.RouterImpl <init>
> > INFORMATION: Creating Router: org.fourthline.cling.transport.RouterImpl
> > Okt 19, 2015 7:59:58 PM org.fourthline.cling.transport.impl.MulticastReceiverImpl init
> > INFORMATION: Creating wildcard socket (for receiving multicast datagrams) on port: 1900
> > Okt 19, 2015 7:59:58 PM org.fourthline.cling.transport.impl.MulticastReceiverImpl init
> > INFORMATION: Joining multicast group: /239.255.255.250:1900 on network interface: en3
> > Okt 19, 2015 7:59:58 PM org.fourthline.cling.transport.impl.StreamServerImpl init
> > INFORMATION: Created server (for receiving TCP streams) on: /192.168.88.253:49393
> > Okt 19, 2015 7:59:58 PM org.fourthline.cling.transport.impl.DatagramIOImpl init
> > INFORMATION: Creating bound socket (for datagram input/output) on: /192.168.88.253
> > Okt 19, 2015 7:59:58 PM org.fourthline.cling.UpnpServiceImpl <init>
> > INFORMATION: <<< UPnP service started successfully
> > SonoAir v1.0 (BETA 4.0)
> > 
> > ## Copyright (c) 2015 Michael Hoffer info@michaelhoffer.de
> > 
> > -> using node-v0.10.28-darwin-x64
> > -> using airsonos by Stephen Wan
> >    see https://github.com/stephen/airsonos/blob/master/LICENSE
> > 
> > ## -> starting airsonos module... [done]
> > 
> > Setting up SonoAir for Schlafzimmer {192.168.88.242:1400}
> > Okt 19, 2015 8:00:12 PM org.fourthline.cling.protocol.RetrieveRemoteDescriptors describeService
> > WARNUNG: Service descriptor retrieval failed: http://192.168.88.242:1400/ssdp/notfound, 404 Not Found
> > Okt 19, 2015 8:00:12 PM org.fourthline.cling.protocol.RetrieveRemoteDescriptors describeServices
> > WARNUNG: Skipping invalid service '(RemoteService) Descriptor: /ssdp/notfound' of: (RemoteDevice) Identity: (RemoteDeviceIdentity) UDN: uuid:RINCON_B8E9375D56BC01400, Descriptor: http://192.168.88.242:1400/xml/group_description.xml, Root: true
> > Okt 19, 2015 8:00:14 PM org.fourthline.cling.protocol.RetrieveRemoteDescriptors describeService
> > WARNUNG: Service descriptor retrieval failed: http://192.168.88.243:1400/ssdp/notfound, 404 Not Found
> > Okt 19, 2015 8:00:14 PM org.fourthline.cling.protocol.RetrieveRemoteDescriptors describeServices
> > WARNUNG: Skipping invalid service '(RemoteService) Descriptor: /ssdp/notfound' of: (RemoteDevice) Identity: (RemoteDeviceIdentity) UDN: uuid:RINCON_B8E9375D551401400, Descriptor: http://192.168.88.243:1400/xml/group_description.xml, Root: true
> > ERROR:    SonoAir does not support the requested codec.
> > SOLUTION: select SonoAir audio source from menu bar (ALT + Primary Mousebutton)
> >           For more information visit:
> >           http://sonoair.mihosoft.eu/codec-not-supported.html

**Comment by jakobl** [comment]
+1

**Comment by miho** [comment]
I have a working prototype since yesterday. Links to experimental builds are announced via Twitter.

**Comment by KarimGeiger** [comment]
@miho thanks for investigating! Sadly, this new version (BETA 5.0) doesn't work either. The Play:1 gets discovered and I'm able to adjust volume and LED but it won't show up in either iTunes nor system settings. This is the full log:

```
>> DEBUG: retryCounter: 0
>> DEBUG: using new discovery method
Nov 07, 2015 4:03:17 AM org.fourthline.cling.UpnpServiceImpl <init>
INFO: >>> Starting UPnP service...
Nov 07, 2015 4:03:17 AM org.fourthline.cling.UpnpServiceImpl <init>
INFO: Using configuration: org.fourthline.cling.DefaultUpnpServiceConfiguration
Nov 07, 2015 4:03:17 AM org.fourthline.cling.transport.RouterImpl <init>
INFO: Creating Router: org.fourthline.cling.transport.RouterImpl
Nov 07, 2015 4:03:17 AM org.fourthline.cling.transport.impl.MulticastReceiverImpl init
INFO: Creating wildcard socket (for receiving multicast datagrams) on port: 1900
Nov 07, 2015 4:03:17 AM org.fourthline.cling.transport.impl.MulticastReceiverImpl init
INFO: Joining multicast group: /239.255.255.250:1900 on network interface: en7
Nov 07, 2015 4:03:17 AM org.fourthline.cling.transport.impl.MulticastReceiverImpl init
INFO: Creating wildcard socket (for receiving multicast datagrams) on port: 1900
Nov 07, 2015 4:03:17 AM org.fourthline.cling.transport.impl.MulticastReceiverImpl init
INFO: Joining multicast group: /239.255.255.250:1900 on network interface: vboxnet0
Nov 07, 2015 4:03:17 AM org.fourthline.cling.transport.impl.StreamServerImpl init
INFO: Created server (for receiving TCP streams) on: /192.168.13.222:55255
Nov 07, 2015 4:03:17 AM org.fourthline.cling.transport.impl.DatagramIOImpl init
INFO: Creating bound socket (for datagram input/output) on: /192.168.13.222
Nov 07, 2015 4:03:17 AM org.fourthline.cling.transport.impl.StreamServerImpl init
INFO: Created server (for receiving TCP streams) on: /192.168.56.1:55256
Nov 07, 2015 4:03:17 AM org.fourthline.cling.transport.impl.DatagramIOImpl init
INFO: Creating bound socket (for datagram input/output) on: /192.168.56.1
Nov 07, 2015 4:03:17 AM org.fourthline.cling.UpnpServiceImpl <init>
INFO: <<< UPnP service started successfully
Nov 07, 2015 4:03:17 AM org.fourthline.cling.UpnpServiceImpl <init>
INFO: >>> Starting UPnP service...
Nov 07, 2015 4:03:17 AM org.fourthline.cling.UpnpServiceImpl <init>
INFO: Using configuration: org.fourthline.cling.DefaultUpnpServiceConfiguration
Nov 07, 2015 4:03:17 AM org.fourthline.cling.transport.RouterImpl <init>
INFO: Creating Router: org.fourthline.cling.transport.RouterImpl
Nov 07, 2015 4:03:17 AM org.fourthline.cling.transport.impl.MulticastReceiverImpl init
INFO: Creating wildcard socket (for receiving multicast datagrams) on port: 1900
Nov 07, 2015 4:03:17 AM org.fourthline.cling.transport.impl.MulticastReceiverImpl init
INFO: Joining multicast group: /239.255.255.250:1900 on network interface: en7
Nov 07, 2015 4:03:17 AM org.fourthline.cling.transport.impl.MulticastReceiverImpl init
INFO: Creating wildcard socket (for receiving multicast datagrams) on port: 1900
Nov 07, 2015 4:03:17 AM org.fourthline.cling.transport.impl.MulticastReceiverImpl init
INFO: Joining multicast group: /239.255.255.250:1900 on network interface: vboxnet0
Nov 07, 2015 4:03:17 AM org.fourthline.cling.transport.impl.StreamServerImpl init
INFO: Created server (for receiving TCP streams) on: /192.168.13.222:55257
Nov 07, 2015 4:03:17 AM org.fourthline.cling.transport.impl.DatagramIOImpl init
INFO: Creating bound socket (for datagram input/output) on: /192.168.13.222
Nov 07, 2015 4:03:17 AM org.fourthline.cling.transport.impl.StreamServerImpl init
INFO: Created server (for receiving TCP streams) on: /192.168.56.1:55258
Nov 07, 2015 4:03:17 AM org.fourthline.cling.transport.impl.DatagramIOImpl init
INFO: Creating bound socket (for datagram input/output) on: /192.168.56.1
Nov 07, 2015 4:03:17 AM org.fourthline.cling.UpnpServiceImpl <init>
INFO: <<< UPnP service started successfully
Nov 07, 2015 4:03:17 AM org.fourthline.cling.transport.impl.DatagramIOImpl send
SEVERE: Exception sending datagram to: /239.255.255.250: java.io.IOException: No route to host
java.io.IOException: No route to host
    at java.net.PlainDatagramSocketImpl.send(Native Method)
    at java.net.DatagramSocket.send(DatagramSocket.java:693)
    at org.fourthline.cling.transport.impl.DatagramIOImpl.send(DatagramIOImpl.java:159)
    at org.fourthline.cling.transport.impl.DatagramIOImpl.send(DatagramIOImpl.java:150)
    at org.fourthline.cling.transport.RouterImpl.send(RouterImpl.java:309)
    at org.fourthline.cling.protocol.async.SendingSearch.execute(SendingSearch.java:91)
    at org.fourthline.cling.protocol.SendingAsync.run(SendingAsync.java:54)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

Nov 07, 2015 4:03:18 AM org.fourthline.cling.transport.impl.DatagramIOImpl send
SEVERE: Exception sending datagram to: /239.255.255.250: java.io.IOException: No route to host
java.io.IOException: No route to host
    at java.net.PlainDatagramSocketImpl.send(Native Method)
    at java.net.DatagramSocket.send(DatagramSocket.java:693)
    at org.fourthline.cling.transport.impl.DatagramIOImpl.send(DatagramIOImpl.java:159)
    at org.fourthline.cling.transport.impl.DatagramIOImpl.send(DatagramIOImpl.java:150)
    at org.fourthline.cling.transport.RouterImpl.send(RouterImpl.java:309)
    at org.fourthline.cling.protocol.async.SendingSearch.execute(SendingSearch.java:91)
    at org.fourthline.cling.protocol.SendingAsync.run(SendingAsync.java:54)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

Nov 07, 2015 4:03:18 AM org.fourthline.cling.transport.impl.DatagramIOImpl send
SEVERE: Exception sending datagram to: /239.255.255.250: java.io.IOException: No route to host
java.io.IOException: No route to host
    at java.net.PlainDatagramSocketImpl.send(Native Method)
    at java.net.DatagramSocket.send(DatagramSocket.java:693)
    at org.fourthline.cling.transport.impl.DatagramIOImpl.send(DatagramIOImpl.java:159)
    at org.fourthline.cling.transport.impl.DatagramIOImpl.send(DatagramIOImpl.java:150)
    at org.fourthline.cling.transport.RouterImpl.send(RouterImpl.java:309)
    at org.fourthline.cling.protocol.async.SendingSearch.execute(SendingSearch.java:91)
    at org.fourthline.cling.protocol.SendingAsync.run(SendingAsync.java:54)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

Nov 07, 2015 4:03:19 AM org.fourthline.cling.transport.impl.DatagramIOImpl send
SEVERE: Exception sending datagram to: /239.255.255.250: java.io.IOException: No route to host
java.io.IOException: No route to host
    at java.net.PlainDatagramSocketImpl.send(Native Method)
    at java.net.DatagramSocket.send(DatagramSocket.java:693)
    at org.fourthline.cling.transport.impl.DatagramIOImpl.send(DatagramIOImpl.java:159)
    at org.fourthline.cling.transport.impl.DatagramIOImpl.send(DatagramIOImpl.java:150)
    at org.fourthline.cling.transport.RouterImpl.send(RouterImpl.java:309)
    at org.fourthline.cling.protocol.async.SendingSearch.execute(SendingSearch.java:91)
    at org.fourthline.cling.protocol.SendingAsync.run(SendingAsync.java:54)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

Nov 07, 2015 4:03:19 AM org.fourthline.cling.transport.impl.DatagramIOImpl send
SEVERE: Exception sending datagram to: /239.255.255.250: java.io.IOException: No route to host
java.io.IOException: No route to host
    at java.net.PlainDatagramSocketImpl.send(Native Method)
    at java.net.DatagramSocket.send(DatagramSocket.java:693)
    at org.fourthline.cling.transport.impl.DatagramIOImpl.send(DatagramIOImpl.java:159)
    at org.fourthline.cling.transport.impl.DatagramIOImpl.send(DatagramIOImpl.java:150)
    at org.fourthline.cling.transport.RouterImpl.send(RouterImpl.java:309)
    at org.fourthline.cling.protocol.async.SendingSearch.execute(SendingSearch.java:91)
    at org.fourthline.cling.protocol.SendingAsync.run(SendingAsync.java:54)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

Nov 07, 2015 4:03:27 AM org.fourthline.cling.protocol.RetrieveRemoteDescriptors describeService
WARNING: Received empty service descriptor:http://192.168.13.26:5000/ssdp/dummy.xml
Nov 07, 2015 4:03:27 AM org.fourthline.cling.protocol.RetrieveRemoteDescriptors describeServices
WARNING: Skipping invalid service '(RemoteService) Descriptor: /ssdp/dummy.xml' of: (RemoteDevice) Identity: (RemoteDeviceIdentity) UDN: uuid:73796E6F-6473-6D00-0000-00113214e03d, Descriptor: http://192.168.13.26:5000/ssdp/desc-DSM-eth0.xml, Root: true
SonoAir v1.0 (BETA 5.0)
Copyright (c) 2015 Michael Hoffer <info@michaelhoffer.de>
--------------------------------------------------------------
-> using node-v0.12.7-darwin-x64
-> using airsonos by Stephen Wan
   see https://github.com/stephen/airsonos/blob/master/LICENSE
-> starting airsonos module...
WARNING: devices ignored (TODO 05.11.2015)
 [done]
--------------------------------------------------------------
Searching for Sonos devices on network...

Nov 07, 2015 4:04:08 AM org.fourthline.cling.protocol.RetrieveRemoteDescriptors describeService
WARNING: Received empty service descriptor:http://192.168.13.26:5000/ssdp/dummy.xml
Nov 07, 2015 4:04:08 AM org.fourthline.cling.protocol.RetrieveRemoteDescriptors describeServices
WARNING: Skipping invalid service '(RemoteService) Descriptor: /ssdp/dummy.xml' of: (RemoteDevice) Identity: (RemoteDeviceIdentity) UDN: uuid:73796E6F-6473-6D00-0000-00113214e03d, Descriptor: http://192.168.13.26:5000/ssdp/desc-DSM-eth0.xml, Root: true
Nov 07, 2015 4:04:27 AM org.fourthline.cling.transport.impl.StreamClientImpl sendRequest
INFO: Timeout of 60 seconds while waiting for HTTP request to complete, aborting: (StreamRequestMessage) GET http://192.168.0.1:1900/igd.xml
Nov 07, 2015 4:04:27 AM org.fourthline.cling.protocol.RetrieveRemoteDescriptors describe
WARNING: Device descriptor retrieval failed, no response: http://192.168.0.1:1900/igd.xml
Nov 07, 2015 4:05:30 AM org.fourthline.cling.transport.impl.StreamClientImpl sendRequest
INFO: Timeout of 60 seconds while waiting for HTTP request to complete, aborting: (StreamRequestMessage) GET http://192.168.0.1:1900/igd.xml
Nov 07, 2015 4:05:30 AM org.fourthline.cling.protocol.RetrieveRemoteDescriptors describe
WARNING: Device descriptor retrieval failed, no response: http://192.168.0.1:1900/igd.xml

```

**Comment by heubergen** [comment]
For me, the app can't even discover the devices.
Also the stop SonoAir button doesn't work, the App doesn't quit his search.

Here's my log:

```
>> Property Folder Options:
 --> using custom property folder suffix, suffix: default
 --> initializing property folder: /Users/patrickalbrecht/.sonoair/1.0-beta-4.0/default
>> DEBUG: retryCounter: 0
>> DEBUG: using new discovery method
Nov 07, 2015 12:38:11 PM org.fourthline.cling.UpnpServiceImpl <init>
INFORMATION: >>> Starting UPnP service...
Nov 07, 2015 12:38:11 PM org.fourthline.cling.UpnpServiceImpl <init>
INFORMATION: Using configuration: org.fourthline.cling.DefaultUpnpServiceConfiguration
Nov 07, 2015 12:38:11 PM org.fourthline.cling.transport.RouterImpl <init>
INFORMATION: Creating Router: org.fourthline.cling.transport.RouterImpl
Nov 07, 2015 12:38:11 PM org.fourthline.cling.transport.impl.MulticastReceiverImpl init
INFORMATION: Creating wildcard socket (for receiving multicast datagrams) on port: 1900
Nov 07, 2015 12:38:11 PM org.fourthline.cling.transport.impl.MulticastReceiverImpl init
INFORMATION: Joining multicast group: /239.255.255.250:1900 on network interface: en3
Nov 07, 2015 12:38:11 PM org.fourthline.cling.transport.impl.StreamServerImpl init
INFORMATION: Created server (for receiving TCP streams) on: /192.168.88.253:49484
Nov 07, 2015 12:38:11 PM org.fourthline.cling.transport.impl.DatagramIOImpl init
INFORMATION: Creating bound socket (for datagram input/output) on: /192.168.88.253
Nov 07, 2015 12:38:11 PM org.fourthline.cling.UpnpServiceImpl <init>
INFORMATION: <<< UPnP service started successfully
Nov 07, 2015 12:38:11 PM org.fourthline.cling.UpnpServiceImpl <init>
INFORMATION: >>> Starting UPnP service...
Nov 07, 2015 12:38:11 PM org.fourthline.cling.UpnpServiceImpl <init>
INFORMATION: Using configuration: org.fourthline.cling.DefaultUpnpServiceConfiguration
Nov 07, 2015 12:38:11 PM org.fourthline.cling.transport.RouterImpl <init>
INFORMATION: Creating Router: org.fourthline.cling.transport.RouterImpl
Nov 07, 2015 12:38:11 PM org.fourthline.cling.transport.impl.MulticastReceiverImpl init
INFORMATION: Creating wildcard socket (for receiving multicast datagrams) on port: 1900
Nov 07, 2015 12:38:11 PM org.fourthline.cling.transport.impl.MulticastReceiverImpl init
INFORMATION: Joining multicast group: /239.255.255.250:1900 on network interface: en3
Nov 07, 2015 12:38:11 PM org.fourthline.cling.transport.impl.StreamServerImpl init
INFORMATION: Created server (for receiving TCP streams) on: /192.168.88.253:49485
Nov 07, 2015 12:38:11 PM org.fourthline.cling.transport.impl.DatagramIOImpl init
INFORMATION: Creating bound socket (for datagram input/output) on: /192.168.88.253
Nov 07, 2015 12:38:11 PM org.fourthline.cling.UpnpServiceImpl <init>
INFORMATION: <<< UPnP service started successfully
>> DEBUG: retryCounter: 1
>> DEBUG: using new discovery method
Nov 07, 2015 12:38:21 PM org.fourthline.cling.UpnpServiceImpl <init>
INFORMATION: >>> Starting UPnP service...
Nov 07, 2015 12:38:21 PM org.fourthline.cling.UpnpServiceImpl <init>
INFORMATION: Using configuration: org.fourthline.cling.DefaultUpnpServiceConfiguration
Nov 07, 2015 12:38:21 PM org.fourthline.cling.transport.RouterImpl <init>
INFORMATION: Creating Router: org.fourthline.cling.transport.RouterImpl
Nov 07, 2015 12:38:21 PM org.fourthline.cling.transport.impl.MulticastReceiverImpl init
INFORMATION: Creating wildcard socket (for receiving multicast datagrams) on port: 1900
Nov 07, 2015 12:38:21 PM org.fourthline.cling.transport.impl.MulticastReceiverImpl init
INFORMATION: Joining multicast group: /239.255.255.250:1900 on network interface: en3
Nov 07, 2015 12:38:21 PM org.fourthline.cling.transport.impl.StreamServerImpl init
INFORMATION: Created server (for receiving TCP streams) on: /192.168.88.253:49486
Nov 07, 2015 12:38:21 PM org.fourthline.cling.transport.impl.DatagramIOImpl init
INFORMATION: Creating bound socket (for datagram input/output) on: /192.168.88.253
Nov 07, 2015 12:38:21 PM org.fourthline.cling.UpnpServiceImpl <init>
INFORMATION: <<< UPnP service started successfully
Nov 07, 2015 12:38:21 PM org.fourthline.cling.UpnpServiceImpl <init>
INFORMATION: >>> Starting UPnP service...
Nov 07, 2015 12:38:21 PM org.fourthline.cling.UpnpServiceImpl <init>
INFORMATION: Using configuration: org.fourthline.cling.DefaultUpnpServiceConfiguration
Nov 07, 2015 12:38:21 PM org.fourthline.cling.transport.RouterImpl <init>
INFORMATION: Creating Router: org.fourthline.cling.transport.RouterImpl
Nov 07, 2015 12:38:21 PM org.fourthline.cling.transport.impl.MulticastReceiverImpl init
INFORMATION: Creating wildcard socket (for receiving multicast datagrams) on port: 1900
Nov 07, 2015 12:38:21 PM org.fourthline.cling.transport.impl.MulticastReceiverImpl init
INFORMATION: Joining multicast group: /239.255.255.250:1900 on network interface: en3
Nov 07, 2015 12:38:21 PM org.fourthline.cling.transport.impl.StreamServerImpl init
INFORMATION: Created server (for receiving TCP streams) on: /192.168.88.253:49487
Nov 07, 2015 12:38:21 PM org.fourthline.cling.transport.impl.DatagramIOImpl init
INFORMATION: Creating bound socket (for datagram input/output) on: /192.168.88.253
Nov 07, 2015 12:38:21 PM org.fourthline.cling.UpnpServiceImpl <init>
INFORMATION: <<< UPnP service started successfully
>> DEBUG: retryCounter: 2
>> DEBUG: using new discovery method
Nov 07, 2015 12:38:31 PM org.fourthline.cling.UpnpServiceImpl <init>
INFORMATION: >>> Starting UPnP service...
Nov 07, 2015 12:38:31 PM org.fourthline.cling.UpnpServiceImpl <init>
INFORMATION: Using configuration: org.fourthline.cling.DefaultUpnpServiceConfiguration
Nov 07, 2015 12:38:31 PM org.fourthline.cling.transport.RouterImpl <init>
INFORMATION: Creating Router: org.fourthline.cling.transport.RouterImpl
Nov 07, 2015 12:38:31 PM org.fourthline.cling.transport.impl.MulticastReceiverImpl init
INFORMATION: Creating wildcard socket (for receiving multicast datagrams) on port: 1900
Nov 07, 2015 12:38:31 PM org.fourthline.cling.transport.impl.MulticastReceiverImpl init
INFORMATION: Joining multicast group: /239.255.255.250:1900 on network interface: en3
Nov 07, 2015 12:38:31 PM org.fourthline.cling.transport.impl.StreamServerImpl init
INFORMATION: Created server (for receiving TCP streams) on: /192.168.88.253:49488
Nov 07, 2015 12:38:31 PM org.fourthline.cling.transport.impl.DatagramIOImpl init
INFORMATION: Creating bound socket (for datagram input/output) on: /192.168.88.253
Nov 07, 2015 12:38:31 PM org.fourthline.cling.UpnpServiceImpl <init>
INFORMATION: <<< UPnP service started successfully
Nov 07, 2015 12:38:31 PM org.fourthline.cling.UpnpServiceImpl <init>
INFORMATION: >>> Starting UPnP service...
Nov 07, 2015 12:38:31 PM org.fourthline.cling.UpnpServiceImpl <init>
INFORMATION: Using configuration: org.fourthline.cling.DefaultUpnpServiceConfiguration
Nov 07, 2015 12:38:31 PM org.fourthline.cling.transport.RouterImpl <init>
INFORMATION: Creating Router: org.fourthline.cling.transport.RouterImpl
Nov 07, 2015 12:38:31 PM org.fourthline.cling.transport.impl.MulticastReceiverImpl init
INFORMATION: Creating wildcard socket (for receiving multicast datagrams) on port: 1900
Nov 07, 2015 12:38:31 PM org.fourthline.cling.transport.impl.MulticastReceiverImpl init
INFORMATION: Joining multicast group: /239.255.255.250:1900 on network interface: en3
Nov 07, 2015 12:38:31 PM org.fourthline.cling.transport.impl.StreamServerImpl init
INFORMATION: Created server (for receiving TCP streams) on: /192.168.88.253:49489
Nov 07, 2015 12:38:31 PM org.fourthline.cling.transport.impl.DatagramIOImpl init
INFORMATION: Creating bound socket (for datagram input/output) on: /192.168.88.253
Nov 07, 2015 12:38:31 PM org.fourthline.cling.UpnpServiceImpl <init>
INFORMATION: <<< UPnP service started successfully
```

**Comment by mreid-tt** [comment]
Looks like we'll have to switch back to command line https://github.com/stephen/airsonos upon which this is based for the time being. I just did an install on my Mac OS X 10.11.1 as follows:
1. Download and install Node.js v4.2.2 from https://nodejs.org/dist/v4.2.2/node-v4.2.2.pkg
2. Launch Terminal
3. Install OSX Command Line Developer Tools with the command: 'xcode-select --install'
4. Install airsonos with the command: 'sudo npm install airsonos -g'

The install will take some time building the deployment and will throw a bunch of warnings. In the end the log will show the following at the end of a successful installation:

```
airsonos@0.2.5 /usr/local/lib/node_modules/airsonos
├── ip@0.3.2
├── flags@0.1.3
├── bluebird@2.10.2
├── sonos@0.7.0 (debug@0.7.4, underscore@1.5.2, async@0.9.2, upnp-client@0.0.1, xml2js@0.2.8, request@2.27.0)
├── nodetunes@0.3.0 (randomstring@1.0.3, random-mac@0.0.4, priorityqueuejs@0.2.0, metricstream@0.0.0, ipaddr.js@1.0.4, httplike@1.0.2, debug@2.2.0, readable-stream@2.0.4, portastic@0.0.1, node-forge@0.6.38, forge@2.3.0, mdns@2.2.10, alac2pcm@1.1.0)
├── nicercast@0.1.0 (icecast-stack@0.3.0, express@3.5.3, lame@1.2.3)
└── babel@5.8.34 (slash@1.0.0, path-exists@1.0.0, path-is-absolute@1.0.0, fs-readdir-recursive@0.1.2, convert-source-map@1.1.2, source-map@0.5.3, commander@2.9.0, output-file-sync@1.1.1, glob@5.0.15, lodash@3.10.1, babel-core@5.8.34, chokidar@1.3.0)
```

Once you're there just run airsonos from the command line as follows:

```
$ airsonos
Searching for Sonos devices on network...
Bedroom (@ 192.168.xxx.xxx:1400, RINCON_XXXXXXXXXXXXXXXXX:1)
Search complete. Set up 1 device tunnel.
```

From there you get to select your device from the system sound menu as well as within iTunes now since this version of the embedded nodetunes 0.3.0 was recently upgraded to support the ALAC codec.

When you are ready to uninstall you can do the following:
1. Launch Terminal
2. Uninstall airsonos with the command: 'sudo npm uninstall airsonos -g'

**Comment by jakobl** [comment]
worked for me. Thank you!

**Comment by miho** [comment]
Did you try the experimental SonoAir build with El Capitan support?

**Comment by mreid-tt** [comment]
@miho No I haven't. Where do I get that? Don't see it at the http://sonoair.mihosoft.eu/download.html website.

**Comment by jakobl** [comment]
i am running the code on OSX 10.11.1 - works great and freakin fast :+1:

**Comment by mreid-tt** [comment]
@miho Okay, I found a link to Beta 5.0 on their twitter feed and I've downloaded it. It seems to be working well. Thanks!

**Comment by hfyeomans** [comment]
Hi, just wanted you to know that I'm on OSX 10.11.3 beta 1 and Sonos 5.0 Beta experimental works great.  I've used it for hours on end, all speakers, and through my ios 9 device without issues so far.  Thanks!

**Comment by hfyeomans** [comment]
Hello again, sorry about the additional update, but anyone using this might find it important.  Upon reboot the Sonos devices would no longer list. So I started testing differnt things.  Using the stop button a bunch of times it would stop searching for devices and list the Sonos(es?). Then I could air play to all my Sonos again.  I stopped the application and started it up again and got it work several times with different results I listed below.
- SonoAir doesn't list speakers, but doesn't say its searching.  Speakers are listed in airplay for all apple devices and plays.
- SonoAir list devices and an additional, non-existent device it warns can't find the name.  All devices except name unkonwn device works.  Unknown device isn't an actual device.
- One attempt I mashed the stop button a bunch of times to cycle through a restart of the search.  I end up with no devices listed, stopped saying it was searching for devices, but then listed each speaker in airplay 5 times.  All playable.
  -There is a 2 second delay, but I would think that is sonos not this application.  I plan on plugging these into a lan swich at my desk for giggles to get off wifi and see if the delay reduces.  Doesn't bother me none since I'm using it for airplay music anyway.  System sounds just go to my monitor speaker.
  -Took two play:1s and made a stereo pair.  That works fine within the same measurements as above for none-stereo pairs.

If there is anything I can provide let me know.

**Comment by ytbryan** [comment]
https://t.co/UEMDv2XTy4 beta 5

**Comment by KarimGeiger** [comment]
Awesome! Thanks, @ytbryan, it seems to work now. It is a bit delayed, though (about 10 seconds), but that's okay.

**Comment by heubergen** [comment]
Is it Async if you watch a video on youtube or just delay?
Because in the meantime I bought a original AirPlay Speaker and this have also a delay but it can handle it in a way it is Sync with a Youtube Video for example.

**Comment by ytbryan** [comment]
Yes there is a delay for YouTube video and big video file like mkv.

Bryan Lim

**Comment by miho** [comment]
Try [1.0 Beta 6](http://sonoair.mihosoft.eu/).

**Comment by ytbryan** [comment]
Thank you for this @miho beta 6 still has a delay and some said that it's normal to have a buffer #18. I wonder is there any method to sync it up when playing videos?
