### ISSUE TITLE
falls when I switch to sonos

### ISSUE THREAD

**Issue by justswan** [miho/SonoAir#15]
swanMBP:airsonos swan$ node ./bin/index.js
Searching for Sonos devices on network...

Living Room (@ 192.168.0.161:1400, RINCON_B8E9379931D601400:32)
Bedroom (@ 192.168.0.54:1400, RINCON_5CAAFD960E5401400:20)
Kitchen (@ 192.168.0.132:1400, RINCON_B8E9373350A601400:48)

Search complete. Set up 3 device tunnels.
crypto.js:238
  this._handle.initiv(cipher, toBuf(key), toBuf(iv));
               ^

Error: Invalid key length
    at Error (native)
    at new Decipheriv (crypto.js:238:16)
    at Object.Decipheriv (crypto.js:235:12)
    at Object.decryptAudioData (/Users/swan/src/airsonos/node_modules/nodetunes/lib/helper.js:141:25)
    at RtpServer.<anonymous> (/Users/swan/src/airsonos/node_modules/nodetunes/lib/rtp.js:32:23)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:191:7)
    at UDP.onMessage (dgram.js:540:8)

**Comment by olets** [comment]
Looks like you meant to post this issue in [airsonos](https://github.com/stephen/airsonos) :) This is a bug in nodetunes, one of the airsonos dependencies, and it's being discussed in stephen/airsonos/issues/302
