### ISSUE TITLE
SonoAir and macOS Mojave

### ISSUE THREAD

**Issue by jasonsyoung** [miho/SonoAir#29]
This worked on 10.13, but on 10.14 Beta (18A326g), I am receiving this. Please open your source to us! (Also fix your versioning, why so many beta versions off by random differences? This is from "v1.0 BETA 7.0"

```bash
bash   [~/Downloads/sonosair] $ SonoAir.app/Contents/MacOS/SonoAir
>> Property Folder Options:
 --> using custom property folder suffix, suffix: default
 --> initializing property folder: /Users/jason/.sonoair/1.0-beta-7.0/default
Jul 09, 2018 6:23:22 PM org.fourthline.cling.UpnpServiceImpl <init>
INFO: >>> Starting UPnP service...
Jul 09, 2018 6:23:22 PM org.fourthline.cling.UpnpServiceImpl <init>
INFO: Using configuration: org.fourthline.cling.DefaultUpnpServiceConfiguration
Jul 09, 2018 6:23:22 PM org.fourthline.cling.transport.RouterImpl <init>
INFO: Creating Router: org.fourthline.cling.transport.RouterImpl
Jul 09, 2018 6:23:22 PM org.fourthline.cling.transport.impl.MulticastReceiverImpl init
INFO: Creating wildcard socket (for receiving multicast datagrams) on port: 1900
Jul 09, 2018 6:23:22 PM org.fourthline.cling.transport.impl.MulticastReceiverImpl init
INFO: Joining multicast group: /239.255.255.250:1900 on network interface: ham0
Jul 09, 2018 6:23:22 PM org.fourthline.cling.transport.impl.MulticastReceiverImpl init
INFO: Creating wildcard socket (for receiving multicast datagrams) on port: 1900
Jul 09, 2018 6:23:22 PM org.fourthline.cling.transport.impl.MulticastReceiverImpl init
INFO: Joining multicast group: /239.255.255.250:1900 on network interface: en0
Jul 09, 2018 6:23:22 PM org.fourthline.cling.transport.impl.StreamServerImpl init
INFO: Created server (for receiving TCP streams) on: /25.74.214.213:51005
Jul 09, 2018 6:23:22 PM org.fourthline.cling.transport.impl.DatagramIOImpl init
INFO: Creating bound socket (for datagram input/output) on: /25.74.214.213
Jul 09, 2018 6:23:22 PM org.fourthline.cling.transport.impl.StreamServerImpl init
INFO: Created server (for receiving TCP streams) on: /192.168.1.176:51006
Jul 09, 2018 6:23:22 PM org.fourthline.cling.transport.impl.DatagramIOImpl init
INFO: Creating bound socket (for datagram input/output) on: /192.168.1.176
Jul 09, 2018 6:23:22 PM org.fourthline.cling.UpnpServiceImpl <init>
INFO: <<< UPnP service started successfully
Jul 09, 2018 6:23:22 PM org.fourthline.cling.UpnpServiceImpl <init>
INFO: >>> Starting UPnP service...
Jul 09, 2018 6:23:22 PM org.fourthline.cling.UpnpServiceImpl <init>
INFO: Using configuration: org.fourthline.cling.DefaultUpnpServiceConfiguration
Jul 09, 2018 6:23:22 PM org.fourthline.cling.transport.RouterImpl <init>
INFO: Creating Router: org.fourthline.cling.transport.RouterImpl
Jul 09, 2018 6:23:22 PM org.fourthline.cling.transport.impl.MulticastReceiverImpl init
INFO: Creating wildcard socket (for receiving multicast datagrams) on port: 1900
Jul 09, 2018 6:23:22 PM org.fourthline.cling.transport.impl.MulticastReceiverImpl init
INFO: Joining multicast group: /239.255.255.250:1900 on network interface: ham0
Jul 09, 2018 6:23:22 PM org.fourthline.cling.transport.impl.MulticastReceiverImpl init
INFO: Creating wildcard socket (for receiving multicast datagrams) on port: 1900
Jul 09, 2018 6:23:22 PM org.fourthline.cling.transport.impl.MulticastReceiverImpl init
INFO: Joining multicast group: /239.255.255.250:1900 on network interface: en0
Jul 09, 2018 6:23:22 PM org.fourthline.cling.transport.impl.StreamServerImpl init
INFO: Created server (for receiving TCP streams) on: /25.74.214.213:51007
Jul 09, 2018 6:23:22 PM org.fourthline.cling.transport.impl.DatagramIOImpl init
INFO: Creating bound socket (for datagram input/output) on: /25.74.214.213
Jul 09, 2018 6:23:22 PM org.fourthline.cling.transport.impl.StreamServerImpl init
INFO: Created server (for receiving TCP streams) on: /192.168.1.176:51008
Jul 09, 2018 6:23:22 PM org.fourthline.cling.transport.impl.DatagramIOImpl init
INFO: Creating bound socket (for datagram input/output) on: /192.168.1.176
Jul 09, 2018 6:23:22 PM org.fourthline.cling.UpnpServiceImpl <init>
INFO: <<< UPnP service started successfully
Jul 09, 2018 6:23:22 PM org.fourthline.cling.transport.impl.DatagramIOImpl send
SEVERE: Exception sending datagram to: /239.255.255.250: java.io.IOException: No route to host
java.io.IOException: No route to host
	at java.net.PlainDatagramSocketImpl.send(Native Method)
	at java.net.DatagramSocket.send(DatagramSocket.java:693)
	at org.fourthline.cling.transport.impl.DatagramIOImpl.send(DatagramIOImpl.java:159)
	at org.fourthline.cling.transport.impl.DatagramIOImpl.send(DatagramIOImpl.java:150)
	at org.fourthline.cling.transport.RouterImpl.send(RouterImpl.java:309)
	at org.fourthline.cling.protocol.async.SendingSearch.execute(SendingSearch.java:91)
	at org.fourthline.cling.protocol.SendingAsync.run(SendingAsync.java:54)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Jul 09, 2018 6:23:22 PM org.fourthline.cling.transport.impl.DatagramIOImpl send
SEVERE: Exception sending datagram to: /239.255.255.250: java.io.IOException: No route to host
java.io.IOException: No route to host
	at java.net.PlainDatagramSocketImpl.send(Native Method)
	at java.net.DatagramSocket.send(DatagramSocket.java:693)
	at org.fourthline.cling.transport.impl.DatagramIOImpl.send(DatagramIOImpl.java:159)
	at org.fourthline.cling.transport.impl.DatagramIOImpl.send(DatagramIOImpl.java:150)
	at org.fourthline.cling.transport.RouterImpl.send(RouterImpl.java:309)
	at org.fourthline.cling.protocol.async.SendingSearch.execute(SendingSearch.java:91)
	at org.fourthline.cling.protocol.SendingAsync.run(SendingAsync.java:54)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

18:23:22.648 [cling-7] DEBUG o.tensin.sonos.model.ZoneAttributes - Zone name: PentHaus, zone icon: x-rincon-roomicon:hallway
DISCOVERED: eu.mihosoft.upnp.sonos.ZonePlayer@52a34046
18:23:22.655 [Thread-14] DEBUG eu.mihosoft.upnp.sonos.ZonePlayers - Adding groups
18:23:22.891 [cling-7] DEBUG o.tensin.sonos.model.ZoneAttributes - Zone name: CC Office, zone icon: x-rincon-roomicon:office
DISCOVERED: eu.mihosoft.upnp.sonos.ZonePlayer@190c198f
18:23:22.892 [Thread-15] DEBUG eu.mihosoft.upnp.sonos.ZonePlayers - Adding groups
18:23:22.901 [cling-10] DEBUG o.tensin.sonos.model.ZoneAttributes - Zone name: RM Office, zone icon: x-rincon-roomicon:living
DISCOVERED: eu.mihosoft.upnp.sonos.ZonePlayer@457c378f
18:23:22.902 [Thread-16] DEBUG eu.mihosoft.upnp.sonos.ZonePlayers - Adding groups
18:23:23.110 [cling-10] DEBUG o.tensin.sonos.model.ZoneAttributes - Zone name: Fun Zone / PT, zone icon: x-rincon-roomicon:pool
DISCOVERED: eu.mihosoft.upnp.sonos.ZonePlayer@79b3f536
18:23:23.110 [Thread-18] DEBUG eu.mihosoft.upnp.sonos.ZonePlayers - Adding groups
18:23:23.118 [cling-12] DEBUG o.tensin.sonos.model.ZoneAttributes - Zone name: SB Office, zone icon: x-rincon-roomicon:living
DISCOVERED: eu.mihosoft.upnp.sonos.ZonePlayer@3e4e36da
18:23:23.119 [Thread-19] DEBUG eu.mihosoft.upnp.sonos.ZonePlayers - Adding groups
Jul 09, 2018 6:23:23 PM org.fourthline.cling.transport.impl.DatagramIOImpl send
SEVERE: Exception sending datagram to: /239.255.255.250: java.io.IOException: No route to host
java.io.IOException: No route to host
	at java.net.PlainDatagramSocketImpl.send(Native Method)
	at java.net.DatagramSocket.send(DatagramSocket.java:693)
	at org.fourthline.cling.transport.impl.DatagramIOImpl.send(DatagramIOImpl.java:159)
	at org.fourthline.cling.transport.impl.DatagramIOImpl.send(DatagramIOImpl.java:150)
	at org.fourthline.cling.transport.RouterImpl.send(RouterImpl.java:309)
	at org.fourthline.cling.protocol.async.SendingSearch.execute(SendingSearch.java:91)
	at org.fourthline.cling.protocol.SendingAsync.run(SendingAsync.java:54)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

>> DEBUG: retryCounter: 0
Jul 09, 2018 6:23:23 PM org.fourthline.cling.transport.impl.DatagramIOImpl send
SEVERE: Exception sending datagram to: /239.255.255.250: java.io.IOException: No route to host
java.io.IOException: No route to host
	at java.net.PlainDatagramSocketImpl.send(Native Method)
	at java.net.DatagramSocket.send(DatagramSocket.java:693)
	at org.fourthline.cling.transport.impl.DatagramIOImpl.send(DatagramIOImpl.java:159)
	at org.fourthline.cling.transport.impl.DatagramIOImpl.send(DatagramIOImpl.java:150)
	at org.fourthline.cling.transport.RouterImpl.send(RouterImpl.java:309)
	at org.fourthline.cling.protocol.async.SendingSearch.execute(SendingSearch.java:91)
	at org.fourthline.cling.protocol.SendingAsync.run(SendingAsync.java:54)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Jul 09, 2018 6:23:24 PM org.fourthline.cling.transport.impl.DatagramIOImpl send
SEVERE: Exception sending datagram to: /239.255.255.250: java.io.IOException: No route to host
java.io.IOException: No route to host
	at java.net.PlainDatagramSocketImpl.send(Native Method)
	at java.net.DatagramSocket.send(DatagramSocket.java:693)
	at org.fourthline.cling.transport.impl.DatagramIOImpl.send(DatagramIOImpl.java:159)
	at org.fourthline.cling.transport.impl.DatagramIOImpl.send(DatagramIOImpl.java:150)
	at org.fourthline.cling.transport.RouterImpl.send(RouterImpl.java:309)
	at org.fourthline.cling.protocol.async.SendingSearch.execute(SendingSearch.java:91)
	at org.fourthline.cling.protocol.SendingAsync.run(SendingAsync.java:54)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Jul 09, 2018 6:23:24 PM eu.mihosoft.upnp.sonos.ZoneGroup getName
SEVERE: null
java.lang.NullPointerException
	at eu.mihosoft.upnp.sonos.ZoneGroup.getName(ZoneGroup.java:68)
	at eu.mihosoft.sonoair.SonoAir.lambda$null$8(SonoAir.java:417)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.util.TimSort.sort(TimSort.java:220)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.ArrayList.sort(ArrayList.java:1454)
	at java.util.Collections.sort(Collections.java:175)
	at eu.mihosoft.sonoair.SonoAir.lambda$rescanAndReRunAirUPNP$9(SonoAir.java:415)
	at java.lang.Thread.run(Thread.java:745)

Jul 09, 2018 6:23:24 PM eu.mihosoft.upnp.sonos.ZoneGroup getName
SEVERE: null
java.lang.NullPointerException
	at eu.mihosoft.upnp.sonos.ZoneGroup.getName(ZoneGroup.java:68)
	at eu.mihosoft.sonoair.SonoAir.lambda$null$8(SonoAir.java:418)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.util.TimSort.sort(TimSort.java:220)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.ArrayList.sort(ArrayList.java:1454)
	at java.util.Collections.sort(Collections.java:175)
	at eu.mihosoft.sonoair.SonoAir.lambda$rescanAndReRunAirUPNP$9(SonoAir.java:415)
	at java.lang.Thread.run(Thread.java:745)

DEBUG: Group with no name: [Group: RINCON_<...snip...>, coordinator: RINCON_<...snip...>, [members: RINCON_<...snip...>]]
DEBUG: Group with no name: [Group: RINCON_<...snip...>, coordinator: RINCON_<...snip...>, [members: RINCON_<...snip...>]]
Jul 09, 2018 6:23:24 PM eu.mihosoft.upnp.sonos.ZoneGroup getName
SEVERE: null
java.lang.NullPointerException
	at eu.mihosoft.upnp.sonos.ZoneGroup.getName(ZoneGroup.java:68)
	at eu.mihosoft.sonoair.SonoAir.lambda$null$8(SonoAir.java:418)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:360)
	at java.util.TimSort.sort(TimSort.java:220)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.ArrayList.sort(ArrayList.java:1454)
	at java.util.Collections.sort(Collections.java:175)
	at eu.mihosoft.sonoair.SonoAir.lambda$rescanAndReRunAirUPNP$9(SonoAir.java:415)
	at java.lang.Thread.run(Thread.java:745)

DEBUG: Group with no name: [Group: RINCON_<...snip...>:28, coordinator: RINCON_B8E93788BB7C01400, [members: RINCON_<...snip...>]]
Jul 09, 2018 6:23:24 PM eu.mihosoft.upnp.sonos.ZoneGroup getName
SEVERE: null
java.lang.NullPointerException
	at eu.mihosoft.upnp.sonos.ZoneGroup.getName(ZoneGroup.java:68)
	at eu.mihosoft.sonoair.SonoAir.lambda$null$8(SonoAir.java:418)
	at java.util.TimSort.binarySort(TimSort.java:296)
	at java.util.TimSort.sort(TimSort.java:221)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.ArrayList.sort(ArrayList.java:1454)
	at java.util.Collections.sort(Collections.java:175)
	at eu.mihosoft.sonoair.SonoAir.lambda$rescanAndReRunAirUPNP$9(SonoAir.java:415)
	at java.lang.Thread.run(Thread.java:745)

DEBUG: Group with no name: [Group: RINCON_<...snip...>:52, coordinator: RINCON_<...snip...>, [members: RINCON_<...snip...>]]
Jul 09, 2018 6:23:24 PM eu.mihosoft.upnp.sonos.ZoneGroup getName
SEVERE: null
java.lang.NullPointerException
	at eu.mihosoft.upnp.sonos.ZoneGroup.getName(ZoneGroup.java:68)
	at eu.mihosoft.sonoair.SonoAir.lambda$null$8(SonoAir.java:418)
	at java.util.TimSort.binarySort(TimSort.java:296)
	at java.util.TimSort.sort(TimSort.java:221)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.ArrayList.sort(ArrayList.java:1454)
	at java.util.Collections.sort(Collections.java:175)
	at eu.mihosoft.sonoair.SonoAir.lambda$rescanAndReRunAirUPNP$9(SonoAir.java:415)
	at java.lang.Thread.run(Thread.java:745)

DEBUG: Group with no name: [Group: RINCON_<...snip...>:15, coordinator: RINCON_<...snip...>, [members: RINCON_<...snip...>]]

Exception: java.lang.NullPointerException thrown from the UncaughtExceptionHandler in thread "Thread-17"
```

 I am also running the latest Sonos Beta 9.0 with a build ID 44255050, so lots of new things that could be interfering.

**Comment by jasonsyoung** [comment]
Also more goodies, when clicking stop:

```bash
DEBUG: Group with no name: [Group: RINCON_<...snip...>:23, coordinator: RINCON_<...snip...>, [members: RINCON_<...snip...>]]
Exception in thread "Thread-19" java.lang.NullPointerException
	at eu.mihosoft.sonoair.SonoAir.lambda$rescanAndReRunAirUPNP$9(SonoAir.java:447)
	at java.lang.Thread.run(Thread.java:745)
Jul 09, 2018 6:29:41 PM org.fourthline.cling.DefaultUpnpServiceConfiguration$ClingExecutor afterExecute
WARNING: Thread terminated org.fourthline.cling.registry.RemoteItems$1@7fa18af9 abruptly with exception: java.lang.NullPointerException
Jul 09, 2018 6:29:41 PM org.fourthline.cling.DefaultUpnpServiceConfiguration$ClingExecutor afterExecute
WARNING: Root cause: java.lang.NullPointerException
Exception in thread "cling-12" java.lang.NullPointerException
	at org.tensin.sonos.control.AbstractService.findService(AbstractService.java:101)
	at org.tensin.sonos.control.MediaServerDevice.<init>(MediaServerDevice.java:49)
	at org.tensin.sonos.control.ZonePlayer.<init>(ZonePlayer.java:109)
	at eu.mihosoft.upnp.sonos.ZonePlayer.<init>(ZonePlayer.java:45)
	at eu.mihosoft.upnp.sonos.ZonePlayers$1.remoteDeviceAdded(ZonePlayers.java:51)
	at org.fourthline.cling.registry.RemoteItems$1.run(RemoteItems.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Jul 09, 2018 6:30:06 PM org.fourthline.cling.protocol.RetrieveRemoteDescriptors describeService
WARNING: Service descriptor retrieval failed: http://192.168.1.170:1400/ssdp/notfound, 404 Not Found
Jul 09, 2018 6:30:06 PM org.fourthline.cling.protocol.RetrieveRemoteDescriptors describeServices
WARNING: Skipping invalid service '(RemoteService) Descriptor: /ssdp/notfound' of: (RemoteDevice) Identity: (RemoteDeviceIdentity) UDN: uuid:RINCON_B8E9375C2BCA01400, Descriptor: http://192.168.1.170:1400/xml/group_description.xml, Root: true
Jul 09, 2018 6:30:35 PM org.fourthline.cling.protocol.RetrieveRemoteDescriptors describeService
WARNING: Service descriptor retrieval failed: http://192.168.1.168:1400/ssdp/notfound, 404 Not Found
Jul 09, 2018 6:30:35 PM org.fourthline.cling.protocol.RetrieveRemoteDescriptors describeServices
WARNING: Skipping invalid service '(RemoteService) Descriptor: /ssdp/notfound' of: (RemoteDevice) Identity: (RemoteDeviceIdentity) UDN: uuid:RINCON_<...snip...>, Descriptor: http://192.168.1.168:1400/xml/group_description.xml, Root: true
Jul 09, 2018 6:31:05 PM org.fourthline.cling.protocol.RetrieveRemoteDescriptors describeService
WARNING: Service descriptor retrieval failed: http://192.168.1.173:1400/ssdp/notfound, 404 Not Found
Jul 09, 2018 6:31:05 PM org.fourthline.cling.protocol.RetrieveRemoteDescriptors describeServices
WARNING: Skipping invalid service '(RemoteService) Descriptor: /ssdp/notfound' of: (RemoteDevice) Identity: (RemoteDeviceIdentity) UDN: uuid:RINCON_<...snip...>, Descriptor: http://192.168.1.173:1400/xml/group_description.xml, Root: true
Jul 09, 2018 6:31:51 PM org.fourthline.cling.protocol.RetrieveRemoteDescriptors describeService
WARNING: Service descriptor retrieval failed: http://192.168.1.174:1400/ssdp/notfound, 404 Not Found
Jul 09, 2018 6:31:51 PM org.fourthline.cling.protocol.RetrieveRemoteDescriptors describeServices
WARNING: Skipping invalid service '(RemoteService) Descriptor: /ssdp/notfound' of: (RemoteDevice) Identity: (RemoteDeviceIdentity) UDN: uuid:RINCON_<...snip...>, Descriptor: http://192.168.1.174:1400/xml/group_description.xml, Root: true
Jul 09, 2018 6:34:23 PM eu.mihosoft.upnp.sonos.ZoneGroup getName
SEVERE: null
java.lang.NullPointerException
	at eu.mihosoft.upnp.sonos.ZoneGroup.getName(ZoneGroup.java:68)
	at eu.mihosoft.sonoair.ZoneGroupWrapper.toString(ZoneGroupWrapper.java:64)
	at eu.mihosoft.sonoair.SonoAir.addDeviceNotification(SonoAir.java:758)
	at eu.mihosoft.sonoair.SonoAir.updateDeviceView(SonoAir.java:468)
	at eu.mihosoft.sonoair.SonoAir.lambda$initMainUI$3(SonoAir.java:307)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Node.fireEvent(Node.java:8411)
	at javafx.scene.control.Button.fire(Button.java:185)
	at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:182)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:96)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:89)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3757)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:352)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:275)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(GlassViewEventHandler.java:388)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:387)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)

Adding device Warning: name not available
Adding device CC Office
Adding device Fun Zone / PT
Adding device MS Office
Adding device PentHaus
Adding device RM Office
Adding device SB Office
Jul 09, 2018 6:34:33 PM eu.mihosoft.upnp.sonos.ZoneGroup getName
SEVERE: null
java.lang.NullPointerException
	at eu.mihosoft.upnp.sonos.ZoneGroup.getName(ZoneGroup.java:68)
	at eu.mihosoft.sonoair.SonoAir.lambda$null$8(SonoAir.java:418)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.util.TimSort.sort(TimSort.java:220)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.ArrayList.sort(ArrayList.java:1454)
	at java.util.Collections.sort(Collections.java:175)
	at eu.mihosoft.sonoair.SonoAir.lambda$rescanAndReRunAirUPNP$9(SonoAir.java:415)
	at java.lang.Thread.run(Thread.java:745)

DEBUG: Group with no name: [Group: RINCON_<...snip...>:52, coordinator: RINCON_<...snip...>, [members: RINCON_<...snip...>]]
Exception in thread "Thread-21" java.lang.NullPointerException
	at eu.mihosoft.sonoair.SonoAir.lambda$rescanAndReRunAirUPNP$9(SonoAir.java:447)
	at java.lang.Thread.run(Thread.java:745)
```

But no devices were added
